### ISSUE TITLE
Hard to read

### ISSUE THREAD

**Issue by arp242** [swalladge/swalladge.net#1]
I though you might be interested to know that I find the text on your site really hard to read due to the thin and low-contrast text:
![screenshot_2019-11-25-11-14-48](https://user-images.githubusercontent.com/1032692/69509709-f9cff580-0f74-11ea-9600-65f8ae766b26.png)

Removing the `font-weight` and re-setting the `text-color` to black (or something near it) makes for a much more pleasant reading experience:
![screenshot_2019-11-25-11-15-30](https://user-images.githubusercontent.com/1032692/69509710-fa688c00-0f74-11ea-972b-615e1ebb9c60.png)

**Comment by arp242** [comment]
Also, your post is on HN FYI: https://news.ycombinator.com/item?id=21624656, in case you didn't see yet :-)

**Comment by swalladge** [comment]
@arp242 Thanks for raising this issue. I haven't observed the text looking as bad as in your top screenshot, but everything you say makes sense. I'll improve the contrast as I get time next. :+1:

To address the following comment from HN:

> Please, please, please, people, don't impose your personal choice of font and background color on the rest of us.

I won't remove colours and font choices altogether - I prefer to have some kind of colourscheme, and if users still hate it they can use their own global font and css overrides. The web would be boring if everything was black and white - hey even HN has has a colourscheme.

I 100% agree that sites should be as readable as possible by default though, so improving the contrast and general readability on the site is top priority for me now.

**Comment by arp242** [comment]
Yeah, I don't agree with that HN comment at all. "Imposing choice of font and colour"? Yeah, because you're really *forced* to read your website 🙄

At any rate, I find that that removing the `font-weight: 300` seems to improve readability more than changing the text colour. I find it "readable enough" by just doing that.

**Comment by swalladge** [comment]
@arp242 pushed some changes; please force reload and let me know if it improves the experience for you. :)

**Comment by arp242** [comment]
Yeah, seems much better :+1: 

![screenshot_2019-11-25-12-55-07](https://user-images.githubusercontent.com/1032692/69513477-d3b15200-0f82-11ea-9334-52f7630ee723.png)

**Comment by swalladge** [comment]
Nice, thanks. :+1:

The font rendering doesn't seem to be as clear as it should be, but perhaps that's more related to your font config?

**Comment by arp242** [comment]
Dunno? Seems good to me? Or at least, no different from anything else. It's just a basic Linux system with a simple WM (dwm).

**Comment by swalladge** [comment]
Ok. I think https://news.ycombinator.com/item?id=21625524 has hit the nail on the head - it will depend on which font you have set by default. Forcing a font-weight then causes fonts that are already light to be really light...

I don't want to manage serving fonts or using a third party cdn like google fonts, and as a user I prefer my default fonts being respected, so I think I'll leave it with just the `sans-serif` hint on the site. Removing the font-weight should solve the issue, which you've confirmed.

I think we can close this issue now. :smile:

**Comment by arp242** [comment]
That comment was made by me, so yeah I agree 😆 And yeah, webfonts come with downsides too,
